// src/components/ProjectDialog.tsx
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { ChevronLeft, ChevronRight } from "lucide-react";
import {
    Carousel,
    CarouselContent,
    CarouselItem,
    CarouselPrevious,
    CarouselNext
} from "@/components/ui/carousel";

export interface ProjectDetails {
    id?: string;
    title: string;
    category: string;
    description: string;
    longDescription?: string;
    technologies?: string[];
    images?: string[];
    liveUrl?: string;
    githubUrl?: string;
}

interface ProjectDialogProps {
    project: ProjectDetails | null;
    open: boolean;
    onOpenChange: (open: boolean) => void;
}

const ProjectDialog = ({ project, open, onOpenChange }: ProjectDialogProps) => {
    const [currentImageIndex, setCurrentImageIndex] = useState(0);

    if (!project) return null;

    const nextImage = () => {
        if (project.images && project.images.length > 0) {
            setCurrentImageIndex((prev) => (prev + 1) % project.images!.length);
        }
    };

    const prevImage = () => {
        if (project.images && project.images.length > 0) {
            setCurrentImageIndex((prev) => (prev - 1 + project.images!.length) % project.images!.length);
        }
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-[700px] p-0 gap-0 overflow-hidden">
                <ScrollArea className="max-h-[80vh]">
                    {/* Project Images */}
                    {project.images && project.images.length > 0 ? (
                        <div className="relative">
                            <Carousel className="w-full" setApi={(api) => {
                                // Optional: Sync external state with carousel api
                                api?.on('select', () => {
                                    setCurrentImageIndex(api.selectedScrollSnap());
                                });
                            }}>
                                <CarouselContent>
                                    {project.images.map((image, index) => (
                                        <CarouselItem key={index}>
                                            <div className="aspect-video bg-secondary flex items-center justify-center">
                                                <p className="text-muted-foreground">Project screenshot {index + 1}</p>
                                            </div>
                                        </CarouselItem>
                                    ))}
                                </CarouselContent>
                                <CarouselPrevious
                                    className="absolute left-2 top-1/2 -translate-y-1/2 bg-background/80 hover:bg-background/90"
                                    onClick={() => setCurrentImageIndex(prev =>
                                        (prev - 1 + project.images!.length) % project.images!.length
                                    )}
                                />
                                <CarouselNext
                                    className="absolute right-2 top-1/2 -translate-y-1/2 bg-background/80 hover:bg-background/90"
                                    onClick={() => setCurrentImageIndex(prev =>
                                        (prev + 1) % project.images!.length
                                    )}
                                />
                            </Carousel>

                            {/* Image counter */}
                            <div className="absolute bottom-2 right-2 bg-background/80 text-foreground text-xs px-2 py-1 rounded-md">
                                {currentImageIndex + 1} / {project.images.length}
                            </div>

                            {/* Image navigation dots */}
                            {project.images.length > 1 && (
                                <div className="absolute bottom-4 left-0 right-0 flex justify-center gap-2">
                                    {project.images.map((_, index) => (
                                        <button
                                            key={index}
                                            className={`w-2 h-2 rounded-full transition-colors ${index === currentImageIndex ? 'bg-primary' : 'bg-muted-foreground/30'
                                                }`}
                                            onClick={() => setCurrentImageIndex(index)}
                                            aria-label={`View image ${index + 1}`}
                                        />
                                    ))}
                                </div>
                            )}
                        </div>
                    ) : (
                        <div className="aspect-video bg-secondary flex items-center justify-center">
                            <p className="text-muted-foreground">No project images</p>
                        </div>
                    )}

                    <div className="p-6">
                        <DialogHeader className="text-left">
                            <DialogTitle className="text-2xl">{project.title}</DialogTitle>
                            <DialogDescription className="text-muted-foreground">{project.category}</DialogDescription>
                        </DialogHeader>

                        <div className="mt-6 space-y-4">
                            {/* Technologies */}
                            {project.technologies && project.technologies.length > 0 && (
                                <div>
                                    <h4 className="text-sm font-medium mb-2">Technologies</h4>
                                    <div className="flex flex-wrap gap-2">
                                        {project.technologies.map((tech, index) => (
                                            <span
                                                key={index}
                                                className="px-2 py-1 text-xs rounded-full bg-secondary text-secondary-foreground"
                                            >
                                                {tech}
                                            </span>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {/* Project Description */}
                            <div>
                                <h4 className="text-sm font-medium mb-2">About this project</h4>
                                <p className="text-base text-muted-foreground">{project.longDescription || project.description}</p>
                            </div>

                            {/* Project Links */}
                            {(project.liveUrl || project.githubUrl) && (
                                <div className="flex gap-4 pt-2">
                                    {project.liveUrl && (
                                        <a
                                            href={project.liveUrl}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="text-sm text-foreground hover:underline"
                                        >
                                            View Live
                                        </a>
                                    )}
                                    {project.githubUrl && (
                                        <a
                                            href={project.githubUrl}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="text-sm text-foreground hover:underline"
                                        >
                                            GitHub Repo
                                        </a>
                                    )}
                                </div>
                            )}
                        </div>
                    </div>
                </ScrollArea>
            </DialogContent>
        </Dialog>
    );
};

export default ProjectDialog;

// resources/js/Components/ProjectDialog.vue
<script setup lang="ts">
import { ref, watch, nextTick } from "vue";
import {
    X,
    ChevronLeft,
    ChevronRight,
    ExternalLink,
    Github,
} from "lucide-vue-next";
import type { Project } from "../types";
const props = defineProps<{ project: Project | null }>();
const emit = defineEmits<{ close: [] }>();
const dialog = ref<HTMLDialogElement | null>(null),
    index = ref(0),
    portrait = ref(false);
watch(
    () => props.project,
    async (project) => {
        index.value = 0;
        portrait.value = false;
        await nextTick();
        if (project) dialog.value?.showModal();
        else dialog.value?.close();
    },
    { immediate: true },
);
function move(direction: number) {
    if (props.project) {
        index.value =
            (index.value + direction + props.project.images.length) %
            props.project.images.length;
        portrait.value = false;
    }
}
function close() {
    dialog.value?.close();
    emit("close");
}
function key(event: KeyboardEvent) {
    if (event.key === "ArrowRight") move(1);
    if (event.key === "ArrowLeft") move(-1);
}
</script>
<template>
    <dialog
        ref="dialog"
        class="portfolio-dialog"
        @cancel.prevent="close"
        @click="
            (e) => {
                if (e.target === dialog) close();
            }
        "
        @keydown="key"
        aria-labelledby="project-title"
    >
        <div v-if="project" class="relative">
            <button
                class="icon-button absolute top-3 right-3 z-10 bg-background/90"
                aria-label="Close project"
                @click="close"
            >
                <X :size="20" />
            </button>
            <div
                v-if="project.images.length"
                class="bg-secondary relative flex justify-center items-center min-h-64"
            >
                <img
                    :key="index"
                    :src="project.images[index]"
                    :alt="project.title + ' — image ' + (index + 1)"
                    class="max-h-[55vh] w-full object-contain"
                    :class="{
                        'max-w-72 my-5 rounded-3xl border-8 border-black':
                            portrait,
                    }"
                    @load="
                        (e) => {
                            const image = e.target as HTMLImageElement;
                            portrait =
                                image.naturalWidth / image.naturalHeight < 0.7;
                        }
                    "
                /><template v-if="project.images.length > 1"
                    ><button
                        class="gallery-prev"
                        @click="move(-1)"
                        aria-label="Previous image"
                    >
                        <ChevronLeft /></button
                    ><button
                        class="gallery-next"
                        @click="move(1)"
                        aria-label="Next image"
                    >
                        <ChevronRight /></button
                    ><span
                        class="absolute bottom-3 left-1/2 -translate-x-1/2 rounded-full px-3 py-1 bg-black/70 text-white text-xs"
                        >{{ index + 1 }} / {{ project.images.length }}</span
                    ></template
                >
            </div>
            <div class="p-6 md:p-8">
                <p class="eyebrow mb-2">{{ project.category }}</p>
                <h2 id="project-title" class="text-2xl">{{ project.title }}</h2>
                <p class="mt-4 text-muted-foreground whitespace-pre-line">
                    {{ project.longDescription || project.description }}
                </p>
                <div class="flex flex-wrap gap-2 my-6">
                    <span
                        v-for="(tech, i) in project.technologies"
                        :key="i"
                        class="badge"
                        >{{ tech }}</span
                    >
                </div>
                <div class="flex flex-wrap gap-3">
                    <a
                        v-if="
                            project.liveUrl &&
                            /^https?:\/\//.test(project.liveUrl)
                        "
                        :href="project.liveUrl"
                        target="_blank"
                        rel="noopener noreferrer"
                        class="button"
                        ><ExternalLink :size="16" />Live Site</a
                    ><a
                        v-if="
                            project.githubUrl &&
                            /^https?:\/\//.test(project.githubUrl)
                        "
                        :href="project.githubUrl"
                        target="_blank"
                        rel="noopener noreferrer"
                        class="button secondary"
                        ><Github :size="16" />Source Code</a
                    >
                </div>
            </div>
        </div>
    </dialog>
</template>
